@startuml
title Cook state 1
[*] --> Idle

Idle --> ChangePosition : Move key input

Idle --> SwitchCooks : 'Switch Cooks' key input
SwitchCooks : Changes current cook being controlled\naffecting stack used for interaction and\nvisual elements of game


Idle --> CheckInteraction : Interact key input
CheckInteraction --> CheckInteractionValid : In valid range of station
CheckInteractionValid --> Idle : Interaction not valid
CheckInteractionValid : check station's critera e.g. PantryBox\nrequires the cook to have an empty \nslot in their stack to add Ingredient to
CheckInteractionValid --> PerformInteraction : Interaction valid
PerformInteraction --> Idle

Idle --> [*]
@enduml